name = "Retro Basic"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A basic retro-themed Hugo theme"
min_version = "0.41.0"

[author]
  name = "ChatGPT"
  homepage = "https://openai.com"